feat: Se agrega component Text Link
ti-tecnologico-de-monterrey-oficial/tec-design-system-ng pull request #188
Opened 2024-09-24 23:01 UTC by t-havila

[DS01-1453](https://tecdemonterrey.atlassian.net/browse/DS01-1453) - Implementar Text Link

## Changes proposed in this PR: 💻

-Se agrega text link component

## Visuals 🎴

![Screenshot_90](https://github.com/user-attachments/assets/560db147-ac02-428a-8281-88f88a2fb66f)
![Screenshot_91](https://github.com/user-attachments/assets/0ae55ac8-6661-4f0b-a2b4-8625c3095048)

## Checklist ✔️

Please check all steps on the checklist

- [✔️ ] My code matches all coding standars.
- [ ✔️] I included the documentation files (.stories.ts).
- [ ✔️] I ran the unit test before sunmitting.
- [ ✔️] My code resolved all of the task's acceptance criteria.

2024-09-24 23:45 UTC, t-juansanchez requested changes

2024-09-24 23:45 UTC, t-juansanchez commented on projects/ds-ng/src/lib/components/bmb-text-link/bmb-text-link.component.html
> +    <section [class]="getClass()">
Si en ambos casos se utiliza el mismo elemento haz el if dentro del section, y si el section va a ser inline-flex, te recomiendo cambiarlo por un span

2024-09-24 23:45 UTC, t-juansanchez commented on projects/ds-ng/src/lib/components/bmb-text-link/bmb-text-link.component.html
> +            @if(this.iconPosition() == 'left' && this.textLinkStyle() == 'icon'){
con el flex direction puedes cambiar el orden de los elementos, por lo que no es necesario agregarlo dos veces

2024-09-24 23:45 UTC, t-juansanchez commented on projects/ds-ng/src/lib/components/bmb-text-link/bmb-text-link.component.html
> +        <a
te conviene utilizar un template para el contenido y no duplicar el codigo... revisa el interactive icon para ver como se utiliza

2024-09-25 01:02 UTC, t-havila commented on projects/ds-ng/src/lib/components/bmb-text-link/bmb-text-link.component.html
> +    <section [class]="getClass()">
Correjido

2024-09-25 01:02 UTC, t-havila commented on projects/ds-ng/src/lib/components/bmb-text-link/bmb-text-link.component.html
> +            @if(this.iconPosition() == 'left' && this.textLinkStyle() == 'icon'){
Correjido

2024-09-25 15:33 UTC, t-juansanchez approved these changes

2024-09-25 15:39 UTC, merged