Se agrega el componente stat-counter
ti-tecnologico-de-monterrey-oficial/tec-design-system-ng pull request #30
Opened 2024-04-02 23:17 UTC by hhavila

- Angular/Ionic - Circular Stat Counter - Jira: https://tecdemonterrey.atlassian.net/jira/software/c/projects/DS01/boards/240?assignee=63629f4ba04e906250c96bc4&selectedIssue=DS01-572

- Se agrego el componente Stat-counter
- Se arreglaron estilos para el input

2024-04-02 23:26 UTC, t-juansanchez requested changes

2024-04-02 23:26 UTC, t-juansanchez commented on projects/ds-ng/src/assets/styles/tokens/_theme.scss
> +      &__field{
Estamos utilizando un guion bajo para los nombres de los componentes

2024-04-02 23:44 UTC, t-juansanchez approved these changes

2024-04-03 14:16 UTC, LizTec57 reviewed
Revisar los comentarios

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/assets/styles/tokens/_theme.scss
> +        &--container-label {
is - not -- for all

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/assets/styles/tokens/_theme.scss
> +      &__stepper{
is one _ not __ for all

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-input/bmb-input.component.html
> -  <div class="bmb__field--container-label"  *ngIf="label">
need to be bmb_field-box or something like that

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-input/bmb-input.component.scss
>    &--label {
is one -

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-input/bmb-input.component.ts
> +    this.style = `bmb_field--input-${this.appearance}`;
is - one not two

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.component.html
> +<div class="bmb__stepper-wrapper">
this class need to be same as the name of the component in this case bmb_stats or bmb_counter whitout the wrapper

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.component.html
> +        class="bmb__stepper-item"
could be bmb_counter-item

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.scss
> +  &-wrapper{
si no esta wrapper en los estilos, estara directo en bmb_counter {}

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.component.html
> +            class="bmb__step-counter"
aqui seria bmb_stats-counter o algo asi

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.scss
> +  &-item::before{
cuando usamos sass puedes hacer 

`&-item {
&::before, &::after {} aqui pones los que se repiten
&::before{} Aca los estilos especificos del before
&::after {}Aca los estilos especificos del after
&.active {}
}`

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.scss
> +  &-item .bmb__step-counter{
no es necesario meterlo en item, puedes dejarlo asi:

&-counter {}

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/lib/components/bmb-stat-counter/bmb-stat-counter.scss
> +  &-item:last-child::after {
revisa bien donde meter los firs-child, .active .completed no es necesario que repitas &-item

2024-04-03 14:16 UTC, LizTec57 commented on projects/ds-ng/src/assets/styles/tokens/_theme.scss
> +        &-item::before{
aca es igual, no es necesario repetir &-item{ } todo puede ir adentro

2024-04-03 19:12 UTC, merged